# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: ocean
  theme_night: # minimal
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'Ngăm'
    description: 'Charity Organization.'
    twitter: ''
  analytics:
    google_analytics: 'G-74NLCD7XMJ'
    baidu_tongji: ''
    google_tag_manager: 'GTM-NM9CN7SM'
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''
    bing: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

# Site footer

footer:
  copyright:
    notice: '© {year} Ngăm. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: '02/01/2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
#    extra_languages:
#      - r
#      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/ngamtheproject/ngamtheproject'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: 'giscus'
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: 'ngamtheproject/ngamtheproject'
      repo_id: 'R_kgDOKSl_1A'
      category: 'Announcements'
      category_id: 'DIC_kwDOKSl_1M4CZj76'
      theme: preferred_color_scheme
      language_code: en
      mapping: pathname
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    publish_mode: editorial_workflow
    local_backend: false
  academicons:
    enable: false

# Citation style

publications:
  date_format: January 2006
  citation_style: apa
